### ISSUE TITLE
Warning in multi-objectives searching with constraints

### ISSUE THREAD

**Issue by Yuz-Wang** [PKU-DAIR/open-box#1]
The following is the configuration:

`opt = Optimizer( objective_function, space, num_objs=2, num_constraints=1, max_runs=500, surrogate_type='prf', acq_type='ehvic', acq_optimizer_type='random_scipy', initial_runs=30, init_strategy='sobol', ref_point=ref_point_search, time_limit_per_trial=4000, random_state=1, )`

The warning prints in the iteration 31:
[openbox.acq_maximizer.ei_optimization_LocalSearch] Local search took already 1000 iterations. Is is maybe stuck in a infinite loop?

Is there anything wrong？

**Comment by jhj0411jhj** [comment]
The warning message occurs in the initial local search step in random_scipy acquisition function optimizer. It means that the local search could still find a config with better acquisition value after 1000 attempts of neighbor looking.
This might appear in specific tasks. If your optimization task doesn't stuck here, you can ignore the warning message.

Please let us know if you have further questions:)
