### ISSUE TITLE
Support for the multi-object func transfer learning 

### ISSUE THREAD

**Issue by xwt1** [PKU-DAIR/open-box#102]
Hello! I noticed in the [transfer learning tutorial](https://open-box.readthedocs.io/en/latest/advanced_usage/transfer_learning.html) that Open-Box currently does not support multi-objective function transfer learning.

For MOBO, the common approach is to identify the Pareto front. Does Open-Box have any existing functionality to support multi-objective Bayesian optimization (MOBO) and the identification of Pareto front lines? If not, are there any ways to do it using open-box?

**Comment by Xbc-gressor** [comment]
Hi @xwt1, Open-Box does not directly support multi-objective function transfer learning now. However, we offer several components that support secondary development. You can build individual models for each target using techniques like RGPE for transfer learning, and utilize multiple transfer learning surrogate models jointly to identify the Pareto front. We provide interfaces for computing the Pareto front as well as the transfer learning models for your use. For further details, please refer to our documentation.
