### ISSUE TITLE
How to use EA optimizer

### ISSUE THREAD

**Issue by CoreLeader** [PKU-DAIR/open-box#11]
Hello, I would like to use your awesome library to solve a *single objective optimization with multiple constraints* with Evolutionary Algorithm. According to your README, I found the OpenBox supports EA. I would be appreciated if you could demonstrate a tiny demo to adopt EA optimizer.

Thank you very much and happy new year.

**Comment by salty-fish-97** [comment]
We are sorry that the EA in OpenBox does not support single-objective optimization with constraints in the current version. 

While OpenBox is originally designed to be a service for Bayesian optimization, it only contains a simple implementation of EA for standard single-objective optimization. We plan to support other algorithms for generalized scenarios in future versions.

Thanks for the issue and wish you a happy new year.
