### ISSUE TITLE
example optimize_multi_objective_with_constraint can't save json

### ISSUE THREAD

**Issue by Dalton2333** [PKU-DAIR/open-box#15]
**Describe the bug**
Hi there, I was running the example optimize_multi_objective_with_constraint.py with opt.get_history().save_json() added to the end of file, and it reports an error. It seems the save_json function in the HistoryContainer() class is used instead of the MOHistoryContainer() class? 

**To Reproduce**
1. Go to 'optimize_multi_objective_with_constraint.py'
2. Add opt.get_history().save_json() to the end of script.
3. Run the example.
4. See error: float() argument must be a string or a number, not 'list'

**Expected behavior**
Exception has occurred: TypeError
float() argument must be a string or a number, not 'list'

Thanks.

**Comment by jhj0411jhj** [comment]
Thanks for your issue. Bug is fixed.
