### ISSUE TITLE
Why can't the re-optimization method be applied to the single-objective optimization with constraints?

### ISSUE THREAD

**Issue by ganfoubudalian** [PKU-DAIR/open-box#16]
![image](https://user-images.githubusercontent.com/19258066/159917211-c5a56d2a-b1ae-42d1-bff6-158918a6df6d.png)

**Comment by salty-fish-97** [comment]
The re-optimization algorithm in OpenBox is a variant of [RGPE](https://arxiv.org/abs/1802.02219v1), which is a transfer learning method proposed only for single-objective problems without constraints. In other words, the converged results are not guaranteed if we directly apply it to multi-objective problems or problems with constraints. We refer to the original paper for more details about RGPE.

**Comment by salty-fish-97** [comment]
The re-optimization algorithm in OpenBox is a variant of [RGPE](https://arxiv.org/abs/1802.02219v1), which is a transfer learning method proposed only for single-objective problems without constraints. In other words, the converged results are not guaranteed if we directly apply it to multi-objective problems or problems with constraints. We refer to the original paper for more details about RGPE.

**Comment by jhj0411jhj** [comment]
Thanks for your issue. The re-optimization method can be applied to the single-objective optimization with constraints now.
