### ISSUE TITLE
Transfer learning for different searching spaces

### ISSUE THREAD

**Issue by shengzeang** [PKU-DAIR/open-box#2]
I have several similar tasks, but some parts of the searched parameters are different. Can I use the transfer learning in this case?

**Comment by jhj0411jhj** [comment]
We are sorry that OpenBox does not support transfer learning on different spaces so far. The implementation is based
on RGPE, which requires the history tasks sharing the same space. Please refer to https://arxiv.org/pdf/1802.02219.pdf for more details.
