### ISSUE TITLE
OpenBox对类别型参数进行参数重要性排序时报错

### ISSUE THREAD

**Issue by znzjugod** [PKU-DAIR/open-box#21]
**Describe the bug**
A clear and concise description of what the bug is. e.g., on which version, xxx fails.
在使用OpenBox对参数重要性排序这个功能时，我输入了一列类别型参数，程序在完成调优后无法输出参数重要性排序，会报错。具体来说，我编写了一个测试压缩算法效率的demo。参数为COMPRESS_LEVEL（整数型），COMPRESS_METHOD（类别型）。其中整数型参数取值为1~9，类别型参数取值为["bz2", "zlib", "gzip"]。具体做法是测试不同COMPRESS_LEVEL和COMPRESS_METHOD组合下，对文件的压缩效率。评价指标分别为压缩时间和压缩率（压缩后文件大小与压缩前文件大小之比）。优化器参数设置如下：   
opt = Optimizer(
        compress,
        space,
        num_objs=2,
        num_constraints=0,
        max_runs=50,
        surrogate_type='auto',
        acq_type='ehvi',
        time_limit_per_trial=30,
        task_id='compress',
        ref_point=[6.97, 2.74],）
使用OpenBox时可以正常调优，但是在使用history.get_importance()函数时，无法对参数重要性进行评估，会报类型错误！

**To Reproduce**
具体错误为：numpy.core._exceptions._UFuncNoLoopError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None
![image](https://user-images.githubusercontent.com/106044623/174565067-ef8e8918-d996-4483-980c-3b15cda0ac33.png)

**Expected behavior**
可以正常输出特征重要性排名

**Outputs and Logs**
If applicable, add outputs and logs to help explain your problem.
具体调优日志如下：
[OpenBox-compress-logs.log](https://github.com/PKU-DAIR/open-box/files/8939185/OpenBox-compress-logs.log)

**Additional context**
当我对类型行特征中的字符串数据转换为数字类型后，该功能又可以正常使用。所以OpenBox是否不支持对类别型参数如字符串等数据进行重要性排序呢？

**Comment by thomas-young-2013** [comment]
Thanks for this feedback! We will fix it as soon as possible!
感谢反馈，我们会以最快的速度解决这个问题

**Comment by znzjugod** [comment]
import numpy as np
import matplotlib.pyplot as plt
from openbox import Optimizer, sp
import time
import zlib
import gzip
import bz2
# Define Search Space
space = sp.Space()
COMPRESS_LEVEL = sp.Int("COMPRESS_LEVEL",1, 9, default_value = 6)
COMPRESS_METHOD = sp.Categorical("COMPRESS_METHOD", ["bz2", "zlib", "gzip"], default_value = "zlib")
space.add_variables([COMPRESS_LEVEL, COMPRESS_METHOD])
#任一可压缩文件
FILE_PATH = 'enwik8'
with open(FILE_PATH, 'rb') as f_in:
   data = f_in.read()    
# Define Objective Function
def compress(config:space):
    params = list(config.get_dictionary().values())
    x1, x2 = params[0], params[1]
    print(x1,x2)
    start = time.time()
    if x2 == "bz2":
        RES = len(bz2.compress(data, x1))
    elif x2 == "zlib":
        RES = len(zlib.compress(data, x1))
    elif x2 == "gzip":
        RES = len(gzip.compress(data, x1))
    end = time.time()
    y1 = end - start
    y2 = len(data) / RES
    result = dict()
    result['objs'] = [y1, y2, ]
    return result
# Run
if __name__ == "__main__":
    opt = Optimizer(
        compress,
        space,
        num_objs=2,
        num_constraints=0,
        max_runs=50,
        surrogate_type='auto',
        acq_type='ehvi',
        time_limit_per_trial=30,
        task_id='compress',
        ref_point=[6.97, 2.74],
    )
    history = opt.run()
    print(history)
# get_importance
    print(history.get_importance(space))

**Comment by salty-fish-97** [comment]
Thanks for the issue! We have updated the feature importance module in the latest version. The changes are:
1) SHAP will not raise errors when the space has categorical hyperparameters;
2) The function ```get_importance``` will return the importance for each objective when there are multiple objectives.
Please check the updates in the latest version. And we will update the release soon.

感谢反馈！我们目前已在最新版本中更新了特征重要性模块。以下是相关改动：
1) SHAP在处理类别型超参数时将不再报错；
2) ```get_importance```方法将对各个目标返回对应特征的重要性。
请在最新的版本中确认以上更新。我们也会在近期将更新提交至Pypi。

**Comment by jhj0411jhj** [comment]
This bug is resolved in <https://github.com/PKU-DAIR/open-box/commit/b840edcf40e374a6a813eb9a03c3424a2cf8d521> and `openbox>=0.7.17`.
