### ISSUE TITLE
Is there some side effects when using ParallelOptimizer?

### ISSUE THREAD

**Issue by yuzizbk** [PKU-DAIR/open-box#23]
At the beginning, I only launch 12 parallel workers. Now for getting result faster，I launch 30 parallel workers. But I find that the result is getting worse in same searching times. Is this as expected?

By the way, the performance of different workers is different. Some runs very faster, maybe triple faster than the slower workers.

**Comment by salty-fish-97** [comment]
For the first question, if you mean the result is getting worse with the same maximum searching iterations while using more parallel workers, the result is as expected. OpenBox suggests the next configurations using a surrogate and updates the surrogate based on previous observations. In **synchronous** settings, the surrogate is updated only when all parallel workers return the results. When using less workers under the same maximum iterations, the surrogate is updated more frequently and is more reliable to suggest good configurations. Empirically, using only one worker leads to the best results under the same maximum iterations while using more workers leads to the best results under the same wall-clock time. It is suggested to slightly add the maximum iterations when using more workers.

For the second matter, it seems normal as the configurations given to different workers are different. Take the LightGBM tuning task as an example. (The example can be found in ```examples/tuning_lightgbm.py```). If the n_estimators in config A and B is 200 and 100, respectively, it takes approximately twice the time to fit a LightGBM model using config A than B.

**Comment by yuzizbk** [comment]
Thanks for your answers.
