### ISSUE TITLE
Comparison with NNI & Ray Tune

### ISSUE THREAD

**Issue by Tonyhao96** [PKU-DAIR/open-box#28]
Hi,

It is a very interesting work.

Have you considered comparing Open-box with two popular HPO frameworks: [Ray Tune](https://github.com/ray-project/ray) and Microsoft [NNI](https://github.com/microsoft/nni)? I did not find them in the KDD paper. I want to know which one can provide better performance.

**Comment by salty-fish-97** [comment]
Thanks for the issue. 

The performance of HPO services may differ in different scenarios. As OpenBox and both two mentioned frameworks have open-source APIs, we suggest comparing them individually based on your personal requirements. A quick example of using OpenBox can be found in [Example](https://github.com/PKU-DAIR/open-box/blob/master/examples/quick_example.py).
