### ISSUE TITLE
How do I pass kwargs to objective function?

### ISSUE THREAD

**Issue by Dalton2333** [PKU-DAIR/open-box#29]
Hi there,

I was trying to pass all the parameters to the objective function, this includes both varying parameters to be determined and fixed parameters. I tried to use Latin Hypercube for initial sampling, and it reminds me that only int and float can be used in Latin Hypercube (constant and categorical are not accepted). 
So I tried to split the parameters into two parts and pass them into the objective function separately. Then I found in optimizer.parallel_smbo.wrapper() the kwargs is set to dict() and I can't pass my fixed parameters into the objective function. 

Was I missing something? How do I pass additional kwargs to the objective function? I would appreciate a relevant example. 

Cheers!

**Comment by jhj0411jhj** [comment]
If you want to pass fixed parameters to objective function, which remain unchanged in every iteration, try to use `partial`:
```python
from functools import partial
obj_func = partial(objective_function, fixed_a=a, fixed_b=b)
# then pass obj_func to optimizer/advisor in initialization.
```

If you want to pass a second part of changeable parameters to objective function, since additional kwargs are not supported in `Optimizer`/`ParallelOptimizer` yet, here I present an alternative way using `Advisor`:
```python
from openbox import Advisor, Observation
advisor = Advisor(...)
for i in range(50):
    config = advisor.get_suggestion()
    y = objective_function(config, fixed_a=a[i], fixed_b=b[i])
    obs = Observation(config=config, objs=[y])
    advisor.update_observation(obs)
```
In this way, the objective function is called by yourself, so you can take control of more details.
And please use `AyncBatchAdvisor` instead of `Advisor` if you are performing parallel evaluation.

Any further questions are welcomed.

**Comment by Dalton2333** [comment]
Thanks for the answer, it was really helpful!

There are a few more questions:

1. I was using gaussian process as the optimizer, is there a way to plot the gaussian process approximation of the objective function during the optimization?

2. In `openbox.core.base.buildsurrogate`, line 131, it seems `create_gp_model()` function doesn't accepts history_hpo_data. How do I pass historical bayesian optimization data into the initial gp model?

3. In order to pass the historical data to the gp model, I tried to create the initial configuration myself and passed it to the advisor as observations. Although I was getting a strange error `Exception has occurred: AssertionError: exception: no description` . Do you know why it is happening? You can reproduce the error using the following code:

```
from openbox import ParallelOptimizer, sp, AsyncBatchAdvisor, Observation
from ConfigSpace import Configuration, ConfigurationSpace

space = sp.Space()
x1 = sp.Real("x1", -0.4, -0.15)
x2 = sp.Real("x2", -0.3, -0.1)
space.add_variables([x1, x2])
advisor = AsyncBatchAdvisor(
    config_space = space,
    num_objs=1,)
values = {"x1": -0.3, "x2": -0.2}
config = Configuration(space, values)
obs = Observation(config, [1])
advisor.update_observation(obs)
```

Cheers!

**Comment by jhj0411jhj** [comment]
1. We will continue the talk in #30 

2. `history_hpo_data` is designed for transfer learning. For optimizing a single task, please `update_observation` to the advisor.

3. Below is the code of `AsyncBatchAdvisor.update_observation`:
```python
def update_observation(self, observation: Observation):
    config = observation.config
    assert config in self.running_configs  # AssertionError
    self.running_configs.remove(config)
    super().update_observation(observation)
```
The `AsyncBatchAdvisor` maintains a list to record the running configs. It is not perfectly designed for updating history observations from previous run. Here I provide a temporary solution. Please append the history config to the `running_configs` list before calling `update_observation`:
```python
advisor.running_configs.append(config)
advisor.update_observation(obs)
```
By the way, please noticed that the parallel locking mechanism is implemented in `ParallelOptimizer`, but not in `AsyncBatchAdvisor` yet. You may need to take care of it when using the bare `AsyncBatchAdvisor`.

**Comment by Dalton2333** [comment]
Thanks for the suggestions!
