### ISSUE TITLE
Is there ask-and-tell interface?

### ISSUE THREAD

**Issue by shengzeang** [PKU-DAIR/open-box#3]
I have some evaluated hyperparameters and I want to know how to register these results to open-box.

I didn't find the demo, and it seems that I have to modify some code myself.

Could you give me some advice? Thank you ~

**Comment by jhj0411jhj** [comment]
We implement `get_suggestion` (ask) and `update_observation` (tell) in the config_advisor of an optimizer. We are sorry that we do not have a demo showing how to register history to OpenBox so far.

If you want to register evaluated configurations, we suggest trying the following codes. Here is a simple example of adding history to an optimizer before optimization:

```python
from openbox import Optimizer, Observation
from openbox import space as sp
from openbox.utils.constants import SUCCESS
from ConfigSpace import Configuration

config_space= ...
optimizer = Optimizer(...)
for config_array, perf in history: 
    config = sp.Configuration(config_space, vector=config_array) # Make sure that config is an instance of Configuration
    observation = Observation(
        config=config, objs=[perf], constraints=None,
        trial_state=SUCCESS, elapsed_time=None,
    )
    optimizer.config_advisor.update_observation(observation)
optimizer.run()
```
