### ISSUE TITLE
Documentation: example of transfer learning

### ISSUE THREAD

**Issue by bbudescu** [PKU-DAIR/open-box#41]
I can see there's a [page](https://open-box.readthedocs.io/en/latest/advanced_usage/transfer_learning.html) in the docs about the transfer learning feature, however, I wasn't able to find a clear example of how to do this with OpenBox.

**Comment by jhj0411jhj** [comment]
@bbudescu  Currently, metadata/instance features are not officially supported in OpenBox.

**Comment by bbudescu** [comment]
I've seen the HyperTune before, but I thought it's not maintained/supported any more, since it only has 4 commits more than a year ago, and couldn't find any documentation for it.
