### ISSUE TITLE
为什么我一直装不上pyrfr，装了两天了

### ISSUE THREAD

**Issue by BaihtSYSU** [PKU-DAIR/open-box#42]
Collecting pyrfr==0.7.0
  Downloading pyrfr-0.7.0.tar.gz (290 kB)
     -------------------------------------- 290.7/290.7 kB 1.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: pyrfr
  Building wheel for pyrfr (setup.py): started
  Building wheel for pyrfr (setup.py): finished with status 'error'
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr: started
  Running setup.py install for pyrfr: finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [6 lines of output]
  warning: build_py: byte-compiling is disabled, skipping.
  
  cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
  regression_wrap.cpp
  C:\Users\16406\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyrfr
  error: subprocess-exited-with-error
  
  Running setup.py install for pyrfr did not run successfully.
  exit code: 1
  
  [6 lines of output]
  C:\Users\16406\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
  regression_wrap.cpp
  C:\Users\16406\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

pyrfr

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by BaihtSYSU** [comment]
I'm stuck at the pip download Pyrfr.
The swig3.0.12 and c++11 compilers have been installed.
![image](https://user-images.githubusercontent.com/118614017/202884796-22322c28-f713-40a2-877f-5d9116b924a5.png)
![1668917024217](https://user-images.githubusercontent.com/118614017/202884808-422057c5-4481-43c2-a7a2-0fcb6c770fdf.png)

**Comment by jhj0411jhj** [comment]
I haven't encountered this problem before. If you are using a conda environment, maybe you can try to install swig by: `conda install swig`. Or you can try to install swig version >= 4.0.

**Comment by wuerwu** [comment]
我也是，痛苦，到现在还没有解决

**Comment by jhj0411jhj** [comment]
@BaihtSYSU @wuerwu 请尝试安装Microsoft Visual C++依赖（参考https://zhuanlan.zhihu.com/p/165008313 ），再尝试是否可以正常安装pyrfr

**Comment by wuerwu** [comment]
哇！！！太感谢了，解决了！！！！

**Comment by jhj0411jhj** [comment]
We have updated the docs. For Windows users who have trouble building wheel for some packages, e.g. ConfigSpace or pyrfr, the error message is like ‘ERROR: Failed building wheel for XXX’ or ‘Microsoft Visual C++ 14.0 is required’, please refer to [(Docs) Install Microsoft Visual C++ Dependencies](https://open-box.readthedocs.io/en/latest/installation/install_microsoft_vc.html).
