### ISSUE TITLE
约束问题-画图

### ISSUE THREAD

**Issue by nebula303** [PKU-DAIR/open-box#47]
可以注意到，如下两张图
![image](https://user-images.githubusercontent.com/72639142/204491312-a17152f0-2aae-4acc-a40b-9bddc755aa3d.png)
![image](https://user-images.githubusercontent.com/72639142/204491368-c8b517b5-b964-4e01-9a5b-dc8e678a1c0d.png)
history在控制台的输出确实是考虑了约束要求，过滤了不满足条件的约束组合，但画图中依然是所有迭代都考虑到了，并未排除不满足约束的条件

**Comment by jhj0411jhj** [comment]
这个图确实有BUG，没有考虑约束情况。我们将进行修复。

**Comment by salty-fish-97** [comment]
你好，OpenBox目前已经支持HTML可视化功能（HTML Visualization），支持对目标，约束，代理模型，参数重要性等多方面可视化。issue中提及的带约束问题的优化，在新的可视化功能界面中通过不同图形区别了满足以及不满足约束的点，并且优化曲线也仅串联符合要求的点。请通过源码下载OpenBox安装后使用新功能。新版本目前未上传PyPi，将会在后续修复小问题后进行更新。

使用方法及可视化结果介绍请见英文文档[HTML Visualization](https://open-box.readthedocs.io/en/latest/visualization/visualization.html)。

感谢对OpenBox的关注。
