### ISSUE TITLE
Need more examples of "ask and tell mode" in the Example docs

### ISSUE THREAD

**Issue by jiang13021** [PKU-DAIR/open-box#60]
I like `ask and tell mode`(using Advisor & Observation), but there is very little introduction in the doc. I have to read the source code instead of just reading the doc.

Hope you guys can give more examples of `ask and tell mode` in the [Example docs](https://open-box.readthedocs.io/en/latest/examples/examples.html)

By the way, is there any difference in performance between these two methods? Is `Advisor & Observation` slower than `Optimizer`?

**Comment by jhj0411jhj** [comment]
Thanks for your issue. We provide [an example of code](https://github.com/PKU-DAIR/open-box/blob/master/examples/ask_and_tell_interface.py) for `ask and tell interface` in the `examples/` in our repo. Adding this example into Example docs is on the plan. 

Most parameters in `Advisor` are the same as those in `Optimizer`, so you can also refer to the description in Optimizer. We will continuously improve our documentations.

For your last question, there is no difference in performance between the two methods. The `Optimizer` provides an encapsulation of the whole optimization process, while the `Advisor` is a part of `Optimizer`. In `Optimizer.run()`, the `optimizer` will get suggestion from `advisor`, run the objective function, and update observation to `advisor` iteratively. When using the `Advisor & Observation` interface, users need to run the objective function themselves.
