### ISSUE TITLE
How does OpenBox compare to Optuna?

### ISSUE THREAD

**Issue by Yura52** [PKU-DAIR/open-box#65]
Optuna is a very popular hyperparameter optimization framework, and currently it is missing in the comparison table:

https://open-box.readthedocs.io/en/latest/#openbox-capabilities

What are the main differences between the projects?

**Comment by chenquzhao** [comment]
emm... Same concerns

**Comment by jhj0411jhj** [comment]
Hi @Yura52 @chenquzhao , we have updated the capability table in docs to include Optuna. 

Optuna supports FIOC hyperparameters, multi-objective optimization, constrained optimization and distributed optimization, but does not support transfer learning (injecting prior knowledge from previous tasks into the current search) while OpenBox does.

Furthermore, according to the their docs (https://optuna.readthedocs.io/en/stable/reference/samplers/index.html), for single-objective optimization, Optuna is mainly based on TPE algorithm, while OpenBox supports TPE, GP-based BO and PRF-based BO algorithms. For multi-objective optimization, Optuna is based on MOTPE and NSGA-II algorithms, while OpenBox supports NSGA-II and more efficient BO methods with MO acquisition functions such as EHVI.
