### ISSUE TITLE
TypeError on M1 mac: expected float, got int

### ISSUE THREAD

**Issue by DimanChauncey** [PKU-DAIR/open-box#78]
**Describe the bug**
type error on M1 mac

**To Reproduce**
My environment: macbook m1 air + openbox 0.8.1 + python 3.11

TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 config_space = get_configspace()
      2 history = load_json(History, filename="./his.json", config_space=config_space)

Cell In[5], line 3, in get_configspace()
      1 def get_configspace():
      2     space = sp.Space()
----> 3     fetch_width = sp.Int("fetch_width", 8, 24, default_value=16, q=4) ##[8,12,16,20,24]

File /opt/homebrew/lib/python3.11/site-packages/openbox/utils/space.py:55, in Int.__init__(self, name, lower, upper, default_value, q, log, meta)
     19 def __init__(self, name: str, lower: int, upper: int, default_value: Union[int, None] = None,
     20              q: Union[int, None] = None, log: bool = False, meta: Optional[Dict] = None) -> None:
     21     """
     22     An integer variable.
     23 
   (...)
     53         Not used by the configuration space.
     54     """
---> 55     super().__init__(name=name, lower=lower, upper=upper,
     56                      default_value=default_value, q=q,
     57                      log=log, meta=meta)

File ConfigSpace/hyperparameters.pyx:1448, in ConfigSpace.hyperparameters.UniformIntegerHyperparameter.__init__()

File ConfigSpace/hyperparameters.pyx:669, in ConfigSpace.hyperparameters.UniformFloatHyperparameter.__init__()

TypeError: Argument 'default_value' has incorrect type (expected float, got int)

**Expected behavior**
run successfully.

**Comment by jhj0411jhj** [comment]
This issue is the same as #69 and will be closed. Please continue discussing in issue #69.
