### ISSUE TITLE
Is there a checkpoint mechanism？

### ISSUE THREAD

**Issue by DimanChauncey** [PKU-DAIR/open-box#79]
According to the official example, each task needs to be resampled randomly at the beginning. 
Is there a checkpoint mechanism? Or can I read the results of previous training and give parameters based on that for the next iteration? What should I do?

**Comment by jhj0411jhj** [comment]
Hi @DimanChauncey, you may use `advisor.save_json(filename)` and `advisor.load_json(filename)` to save and load existing observations.
