### ISSUE TITLE
ask help on visualization

### ISSUE THREAD

**Issue by DimanChauncey** [PKU-DAIR/open-box#80]
<img width="861" alt="image" src="https://github.com/PKU-DAIR/open-box/assets/44086181/2c7d8cfb-cdf6-4966-8783-35bd7a334b1d">
The label and scale on the y-axis of this picture are too close. How to adjust the distance？
<img width="859" alt="image" src="https://github.com/PKU-DAIR/open-box/assets/44086181/cbb82e26-194a-409e-85fc-b770f95a7421">
How to adjust the starting scale of the x-axis and y-axis? This picture is mostly blank.

Thanks for helping!

**Comment by Xbc-gressor** [comment]
We have updated the 2D Pareto frontier chart, enabling zooming and scaling using the dataZoom component similar to other charts. This feature will be included in the upcoming release version. In the meantime, you can utilize this functionality by installing from the source code. Thank you for your patience and understanding!
